Presentación del conjunto de datos:
Se seleccionan datos correspondinete a una entidad bancaria potugueza que realiza campañas de marketing digital,
en la cual a partir de llamadas se hace ofrecimiento al cliente de producto de crédito a plazos.
En esta, la variable respuesta será si el cliente decide o no tomar el producto ofrecido por la entidad en la llamada.

Importamos los datos

In [1]:
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import requests
from io import StringIO

In [2]:
file_id = "1sfd6TnOHhrCq0I1TusC9HoRwgTtXohFr"
url = f"https://drive.google.com/uc?export=download&id={file_id}"

response = requests.get(url)
df_bank = pd.read_csv(StringIO(response.text), sep=';')

In [3]:
df_bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

In [4]:
df_bank.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

La base cuenta con 16 variables, en las cuales no encontramos valores nulos

In [5]:
df_bank.describe()

,age,balance,day,duration,campaign,pdays,previous
count,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000
mean,40.936210,1362.272058,15.806419,258.163080,2.763841,40.197828,0.580323
std,10.618762,3044.765829,8.322476,257.527812,3.098021,100.128746,2.303441
min,18.000000,-8019.000000,1.000000,0.000000,1.000000,-1.000000,0.000000
25%,33.000000,72.000000,8.000000,103.000000,1.000000,-1.000000,0.000000
50%,39.000000,448.000000,16.000000,180.000000,2.000000,-1.000000,0.000000
75%,48.000000,1428.000000,21.000000,319.000000,3.000000,-1.000000,0.000000
max,95.000000,102127.000000,31.000000,4918.000000,63.000000,871.000000,275.000000

In [6]:
df_bank.y.value_counts()

y
no     39922
yes     5289
Name: count, dtype: int64

In [7]:
from pathlib import Path

In [8]:
ruta_datos_crudos = Path.cwd().resolve().parent / "datos"
ruta_datos_crudos

WindowsPath('C:/Users/aical/Documents/JM_SD_SC_marketing_bancario/datos')

In [9]:
df_bank_clean = df_bank.copy()
for col in df_bank_clean.select_dtypes(include='category').columns:
    df_bank_clean[col] = df_bank_clean[col].astype(str)

In [10]:
ruta_archivo = ruta_datos_crudos / "01_datos_crudos_banko.parquet"

ruta_datos_crudos.mkdir(parents=True, exist_ok=True)

df_bank.to_parquet(ruta_archivo, index=False)